project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Ex/Hands-on_Ex1.qmd
          - text: Hands-on Exercise 2
            href: Hands-on_Ex/Hands-on_Ex2.qmd
          - text: Hands-on Exercise 3
            href: Hands-on_Ex/Hands-on_Ex3.qmd
          - text: Hands-on Exercise 4
            href: Hands-on_Ex/Hands-on_Ex4.qmd
          - text: Hands-on Exercise 5
            href: Hands-on_Ex/Hands-on_Ex5.qmd
      - text: Take-Home Exercises
        menu:
          - text: Take-Home Exercise 1
            href: Take-Home_Ex/Take-Home Ex1.qmd
          - text: Take-Home Exercise 2
            href: Take-Home_Ex/Take-Home Ex2.qmd
          - text: Take-Home Exercise 3
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

