---
title: "Take-Home Exercise 2 - Geospatial Analytics for Social Good"
editor: visual
---

## 1. Overview

### 1.1. Background

The process of creating regions is called [regionalisation](https://www.researchgate.net/publication/28153673_Supervised_Regionalization_Methods_A_Survey/link/0fcfd5094046b13d35000000/download). A regionalisation is a special kind of clustering where the objective is to group observations which are similar in their statistical attributes, but also in their spatial location. In this sense, regionalization embeds the same logic as standard clustering techniques, but also applies a series of geographical constraints. Often, these constraints relate to connectivity: two candidates can only be grouped together in the same region if there exists a path from one member to another member that never leaves the region. These paths often model the spatial relationships in the data, such as contiguity or proximity. However, connectivity does not always need to hold for all regions, and in certain contexts it makes sense to relax connectivity or to impose different types of geographic constraints.

### 1.2. Overall Goal

This study aims to apply appropriate clustering techniques to reveal the spatial patterns of water points in Nigeria.

### 1.3. Key Objectives

Using the appropriate R packages, we will need to:

-   Prepare the dataset and save it in simple feature data frameformat, as well as derive the proportion of functional and non-functional water point at LGA level

-   Conduct thematic mapping analysis to examine the spatial distribution of functional and non-functional water point rate at LGA level

-   Conduct hotspot areas and outliers/clusters maps of functional and non0functional water point rate at LGA level
